README.md, __tests__/label.test.js, lib/configuration.js
- Better usage instructions in readme.
=> Doc: Update README

index.js
- Ensure bot validates and returns appropriate status during pr synchronize.
=> (bugfix) Ensure handling of pull_request.synchronize event. 

__tests__/milestone.test.js, lib/milestone.js
- Fix milestone mergeable check description. Missing a quote.
=> (bugfix) Milestone description missing a quote.

README.md
- Add a screenshot to the README
=> (doc) Add screenshot

__fixtures__/helper.js, __tests__/approvals.test.js, __tests__/configuration.test.js, __tests__/handler.test.js, __tests__/label.test.js, __tests__/milestone.test.js, __tests__/title.test.js, index.js, lib/configuration.js, lib/handler.js
- Extract handle functions to a lib.
- Unit tests for handlers.
=> (chore) Refactor test handler

README.md, __tests__/handler.test.js
- Handler tests were failing silently due to `UnhandledPromiseRejection`. Fixed exceptions being swallowed by it.
- Fixed the tests that were failing due to empty body in the mock.
- Update and fix README with new features that's implemented as well as advanced configuration options.
=> (fix) Fix handler tests and update README.

__tests__/approvals.test.js, lib/approvals.js, lib/processor.js
=> required reviewers feature implemented

README.md
There are a number of improvements merged. README updated.
=> Update README with the latest improvements

__fixtures__/helper.js, __tests__/approvals.test.js, lib/approvals.js
=> fix bug where pr creator is also required as a reviewer

__tests__/approvals.test.js, lib/approvals.js, package.json
closes #32 
NOTE: this PR adds a new package `lodash`, npm install will be required after merging
=> fix bug where old approvals are counted toward requirement

__tests__/description.test.js, lib/description.js, lib/processor.js
=> description advanced settings implemented

__fixtures__/helper.js, __tests__/handler.test.js, lib/checks.js, lib/handler.js
=> use Checks instead of creating status + fix Tests

__tests__/approvals.test.js, lib/approvals.js, lib/configuration.js
based on feed backs (some complaint about having default approval count 1), it is removed in this PR
=> remove default approvals count 1

docs/README.md
=> (doc) Update README with gitter badge.

lib/handler.js
closes #72 
Screen shot of the error message
=> show `action_requested` if error occurs

__fixtures__/helper.js, __tests__/configuration.test.js, __tests__/handler.test.js, __tests__/label.test.js, __tests__/mergeable.test.js, __tests__/validators/label.test.js, __tests__/validators/title.test.js, __tests__/validators/validator.test.js, index.js, lib/configuration.js, lib/handler.js, lib/mergeable.js, lib/validators/label.js, lib/validators/title.js, lib/validators/validator.js, package.json
Lay the initial foundational structure for the new flexible and modular configuration.
- Added nodemon for development.
- Added detection for version 2 as set in env but still be backward compatible.
- Initial validation processing structure.
- Converted Label and Title and some basic unit tests. More conversion needed.
- This is close. Details of the configuration may evolve a little as we code the rest out.
- As per [Documentation](https://www.notion.so/mergeability/Flex-9902182a9f9c4b1c80718f4c4c148fa7)
- Fully backward compatible through environment variable. Either run with version 1 or 2 enabled.
=> Initial infrastruture for Flexible Configuration

__tests__/configuration/transformers/v1Config.test.js, lib/configuration/lib/consts.js, lib/configuration/transformers/v1Config.js
=> v1Config transformer + tests

__tests__/actions/action.test.js, lib/actions/action.js, lib/eventAware.js
=> action class + test

__tests__/validators/options_processor/options.test.js, __tests__/validators/options_processor/options/and.test.js, __tests__/validators/options_processor/options/begins_with.test.js, __tests__/validators/options_processor/options/ends_with.test.js, __tests__/validators/options_processor/options/lib/consolidateResults.test.js, __tests__/validators/options_processor/options/max.test.js, __tests__/validators/options_processor/options/min.test.js, __tests__/validators/options_processor/options/must_exclude.test.js, __tests__/validators/options_processor/options/must_include.test.js, __tests__/validators/options_processor/options/no_empty.test.js, __tests__/validators/options_processor/options/or.test.js, __tests__/validators/options_processor/options/required.test.js, lib/validators/options_processor/options.js, lib/validators/options_processor/options/and.js, lib/validators/options_processor/options/begins_with.js, lib/validators/options_processor/options/ends_with.js, lib/validators/options_processor/options/lib/andOrProcessor.js, lib/validators/options_processor/options/lib/consolidateResults.js, lib/validators/options_processor/options/lib/constructErrorOutput.js, lib/validators/options_processor/options/lib/constructOutput.js, lib/validators/options_processor/options/max.js, lib/validators/options_processor/options/min.js, lib/validators/options_processor/options/must_exclude.js, lib/validators/options_processor/options/must_include.js, lib/validators/options_processor/options/no_empty.js, lib/validators/options_processor/options/or.js, lib/validators/options_processor/options/required.js, package.json
@jusx This is an independent Unit, the CI should be passing for this, please review this one first
=> Options processor + tests

__tests__/validators/options_processor/owners.test.js, lib/validators/options_processor/gitPattern.js, lib/validators/options_processor/owners.js
@jusx This is also another independent, ready to be merged
=> owners option + gitPattern, and tests

__tests__/configuration/configuration.test.js, lib/configuration/configuration.js, lib/configuration/lib/consts.js, lib/configuration/transformers/v2Config.js
=> configuration Class + test

__tests__/actions/checks.test.js, __tests__/actions/comments.test.js, lib/actions/action.js, lib/actions/checks.js, lib/actions/comments.js, lib/actions/handlebars/populateTemplate.js
=> checks action + comment action + tests

__tests__/validators/approval.test.js, lib/validators/approval.js
=> approval validator + test

__fixtures__/helper.js, __tests__/milestone.test.js, __tests__/validators/milestone.test.js, __tests__/validators/project.test.js, lib/validators/milestone.js, lib/validators/options_processor/deepValidation.js, lib/validators/project.js
milestone
[EDIT] also added project validation since they share dependencies
=> milestone validation + test

__tests__/validators/stale.test.js, lib/validators/stale.js
=> stale validation + test

__fixtures__/helper.js, __tests__/description.test.js, lib/processor.js
closes #98 
Please see comments for more information about the bug https://github.com/jusx/mergeable/issues/98#issuecomment-426302899
=> fix #98 + test to mimic the same scenario

index.js, lib/mergeable.js, package.json
Clearly log Mergeable version during startup.
=> Clearly Log Version During Startup

__tests__/validators/options_processor/options/lib/consolidateResults.test.js, lib/actions/handlebars/populateTemplate.js, lib/configuration/configuration.js, lib/configuration/lib/consts.js, lib/mergeable.js, lib/validators/dependent.js, lib/validators/options_processor/options.js, lib/validators/options_processor/options/lib/consolidateResults.js, lib/validators/options_processor/options/max.js, lib/validators/project.js
Context 
---
We want to display information of each validations that that were ran and display it in checks by default.
Things Changed
---
- Added validator name field to outputs from processor
- Added handlebars template string to go through each validation suite and display them
Note: Not well tested yet! [EDIT: it's working]
Default template looks like following
---
=> Default Checks output template

lib/approvals.js, lib/assignee.js, lib/checks.js, lib/configuration.js, lib/dependent.js, lib/description.js, lib/handler.js, lib/issues.js, lib/label.js, lib/milestone.js, lib/owners.js, lib/parseOwners.js, lib/processor.js, lib/projects.js, lib/stale.js, lib/title.js
Goal
---
Mark the deprecated files so it can be easily removed after release
=> add @deprecated to file not used in flex

docs/README.md
- Make corrections to the milestone and project examples for advanced configuration.
=> Correction to example config of milestone and project.

lib/mergeable.js
Goal
---
Log Repo name when an event is received to help debug
=> Log repo name

lib/actions/checks.js, lib/eventAware.js, lib/flex.js, lib/stats/extractValidationStats.js, lib/validators/approval.js, lib/validators/assignee.js, lib/validators/dependent.js, lib/validators/description.js, lib/validators/label.js, lib/validators/milestone.js, lib/validators/project.js, lib/validators/title.js
Goal
---
Make sure that checks are re ran properly when an milestone is added/removed
=> Milestone check

__tests__/validators/approval.test.js, lib/validators/approvals.js
Goal 
---
Fix typo in approval.js to approvals.js
=> Fix approval file name

__fixtures__/helper.js, __tests__/configuration/configuration.test.js, lib/configuration/configuration.js
Goal
---
Only use the config from PR head branch iff it is modified/deleted
=> only use config from PR if its changed

__tests__/configuration/transformers/v1Config.test.js, lib/configuration/transformers/v1Config.js, lib/eventAware.js
Goal
---
Make sure that pull_request_reivew.* is added as default when transforming v1 config
=> add pull_request_review.* as default in v1Config transformer

lib/validators/milestone.js
Goals
---
fix deep validation for milestone
=> fix milestone deep validation

lib/actions/checks.js, lib/validators/approvals.js, lib/validators/assignee.js, lib/validators/dependent.js, lib/validators/description.js, lib/validators/label.js, lib/validators/milestone.js, lib/validators/project.js, lib/validators/title.js
Goal
---
Fix that checks weren't running when assignee is added/removed
=> add assigned and unassigned to support events

__tests__/configuration/transformers/v2Config.test.js, lib/configuration/transformers/v2Config.js
- Fixes default for flex config when recipe includes `pull_request.*`
- Update tests to be more accurate for testing these scenarios.
=> fix: Defaults for flex config

__tests__/actions/comment.test.js, __tests__/validators/title.test.js, lib/actions/comment.js, lib/configuration/lib/consts.js, lib/validators/assignee.js, lib/validators/description.js, lib/validators/label.js, lib/validators/milestone.js, lib/validators/project.js, lib/validators/title.js
Fixes Comment action and extending it's capabilities of events.
- Fixes `Comment` action name as it is more logical to be singular since it creates a single comment.
- Fixes the action so that it can be invoked for any event.
- Fixes the title validator to be async.
- Fixes relevant validators to support any `issues` event.
- Fixes `Assignee` class name so that it will not crash when specified in the configuration.
=> fix: Comment action

__tests__/validators/approvals.test.js
Goal
---
Un-comment the skipped tests in approvals.test.js and fix them
Context
---
The mock data used for certain tests weren't mocked properly
=> Fix approval tests

__tests__/configuration/transformers/v1Config.test.js
Goal
---
add tests regarding and/or config in v1Config transformer
=> add test for and/or v1Config transformation

lib/configuration/lib/consts.js
Goal
---
Current default fail case copy is ambigious
=> copy update for default issue fail and error cases

.circleci/config.yml, __tests__/configuration/configuration.test.js, circle.yml, lib/configuration/configuration.js
Fixes scenario where mergeable was not pulling the config from the PR when a review is submitted.
- Updated code to also retrieve from PR modified files when `pull_request_review` event is triggered
- Updated code to retrieve from PR modified files when the config file is added.
- Updated configuration unit test.
=> fix: scenario for modified|added mergeable config and pull_request_review

__tests__/mergeable.test.js, lib/mergeable.js
We need this to help debug schedule as it seem to be triggering comments on things it shouldn't. We need to turn scheduler on and off without re-deploy.
Added ability to turn off scheduler based on env variable..
=> feat(schedule): add toggle option to turn on/off scheduler on start.

__fixtures__/helper.js, __tests__/mergeable.test.js, lib/actions/checks.js, lib/mergeable.js
To explicitly monitor check completions by repo.
- Instrument checks with debug logs.
- Use a child logger with the right name in mergeable execute function.
- Update tests to have the right fixtures since we are now using `log.child()`.
=> chore(logging): Use bunyan for logging and add debug logs in checks.

docs/README.md
Goal
---
Document examples of and/or options
closes #76
=> docs: add and/or options to read me

docs/README.md, lib/validators/options_processor/options/begins_with.js, lib/validators/options_processor/options/ends_with.js
Goal
---
For more context, look at the issue below 
closes #158
=> fix: match subOption to accept and process array inputs

docs/README.md, lib/validators/options_processor/options/begins_with.js, lib/validators/options_processor/options/ends_with.js
Adds unit tests to #162 
- updates to `begins_with` and `ends_with` sub-option tests with some DRY refactoring.
- Added a single test for arrays to `title` validator.
NOTE: Do not merge until #162 is merged.
=> test(begins_with, ends_with): match option with array

__tests__/validators/options_processor/options/begins_with.test.js, __tests__/validators/options_processor/options/ends_with.test.js, __tests__/validators/title.test.js
Tests of the suboptions -- accidentally omitted from #163 :(
=> test: adds tests to begins_with, title, etc.

.circleci/config.yml, docs/README.md, package.json
Install codecov
- configure code coverage to be uploaded to codecov
- add badge to README
=> chore: install codecov

__tests__/validators/approvals.test.js, __tests__/validators/options_processor/options/required.test.js, lib/validators/approvals.js, lib/validators/options_processor/options/required.js
=> fix(approvals): bug where approval is fetching owners file when not necessary

__fixtures__/helper.js, __tests__/validators/approvals.test.js, lib/validators/approvals.js
Takes care of #174 
- Added pagination when pulling in reviews.
- Added paginate to the mock context
=> fix(approvals): ensure pagination when evaluating review submissions

docs/README.md
- Updated the dependent validator section to include the `changed` option.
- Updated the dependent files recipe section to use the `changed` option instead.
=> docs: update dependent documentation

.github/mergeable.yml
- Allow mergeable when either maintainers approves the PR.
=> chore: change required approvers to OR.

__tests__/interceptors/checkReRun.test.js, lib/interceptors/checkReRun.js
There is a bug in checkReRun class where the condition is process reRun is not correct.
=> fix: condition in which reRun is process

docs/README.md, lib/flex.js, package.json
Updates some references to the old repository in various places.
=> docs: Update Github repo links

docs/README.md
It seems that `project` validator only accepts must_include option in our codebase. It is misleading, we'll need to fix that in the future
=> fix: readme with some inconsistencies that were discovered

__tests__/unit/validators/stale.test.js, lib/validators/stale.js
=> fix: replace deprecated search.issues() with search.issuesAndPullRequests

docs/README.md
=> docs: add clarity around default checks behaviors

__tests__/unit/configuration/configuration.test.js, lib/configuration/configuration.js, lib/flex.js, lib/register.js, lib/registry.js
closes #224 
output : 
@jusx please pay a closer attention to this PR, it has some refactoring involved for better separation
=> feat: catch non existant validator n action error

__fixtures__/unit/helper.js, lib/configuration/configuration.js
=> fix: replace deprecated properties

__tests__/unit/validators/options_processor/options/and.test.js, __tests__/unit/validators/options_processor/options/or.test.js, lib/validators/options_processor/options/lib/andOrProcessor.js, package.json
=> feat: add error catching to and/or option processor

index.js, lib/actions/action.js, lib/actions/assign.js, lib/actions/checks.js, lib/actions/comment.js, lib/actions/labels.js, lib/actions/request_review.js, lib/flex.js, lib/logger.js, lib/mergeable.js, lib/validators/approvals.js, lib/validators/assignee.js, lib/validators/dependent.js, lib/validators/description.js, lib/validators/label.js, lib/validators/milestone.js, lib/validators/or.js, lib/validators/project.js, lib/validators/size.js, lib/validators/stale.js, lib/validators/title.js, lib/validators/validator.js, package.json
Set up logging module and clean up logging to be more verbose
=> feat: set up logging module and structure

__tests__/unit/validators/and.test.js, __tests__/unit/validators/or.test.js, docs/README.md, lib/actions/action.js, lib/flex.js, lib/mergeable.js, lib/validators/and.js, lib/validators/lib/andOrValidatorProcessor.js, lib/validators/validator.js
'And' at Validator level 
Note: contains refactoring of 'Or' validator to reuse the code
closes #216 
closes #191
=> feat: And validator

__tests__/unit/validators/approvals.test.js, docs/README.md, lib/validators/approvals.js, lib/validators/options_processor/options/required.js, lib/validators/options_processor/requestedReviewers.js
Add a sub option `requested_reviewers` for approvals
for more context, see #215 
Note: this only implement the latter part of #215
=> feat: approval - requested reviewers

__tests__/unit/validators/approvals.test.js, docs/README.md, lib/validators/approvals.js, lib/validators/validator.js
Note *** written on top of PR #265 , please only review this after that one has merged.
block merging when an reviewer have requested changes
config
```
do: approvals
block:
changes_requested: true 
message: 'custom Message'
```
closes #215
=> feat: approval - Changes requested

__fixtures__/unit/helper.js, __tests__/unit/actions/close.test.js, docs/README.md, lib/actions/close.js
added 'close' action to close issue or PR 
```
- do: close
```
closes #234
=> feat: 'close' action

docs/README.md
Add a note in readMe about utilizing yaml anchor references to reduce duplication
closes #281
=> docs: add a note in the readMe about utilizing anchor for reusability

__tests__/unit/flex.test.js, __tests__/unit/validators/and.test.js, __tests__/unit/validators/dependent.test.js, __tests__/unit/validators/options_processor/options/and.test.js, __tests__/unit/validators/or.test.js, __tests__/unit/validators/stale.test.js, lib/validators/approvals.js, package.json
Updates some of the dependencies to fix vulnerabilities reported by
Snyk:
- https://snyk.io/vuln/SNYK-JS-CODECOV-543183
- https://snyk.io/vuln/SNYK-JS-CODECOV-548879
- https://snyk.io/vuln/SNYK-JS-DOTPROP-543489
- https://snyk.io/vuln/SNYK-JS-YARGSPARSER-560381
- https://snyk.io/vuln/npm:braces:20180219
- https://snyk.io/vuln/npm:eslint:20180222
The new version of Standard has some stricter linting which required
some minor style changes in some files.
=> chore: Update dependencies

lib/mergeable.js
Just correcting the log statement. 
Production schedule interval is 1000 seconds but log statement  says 2 seconds...
=> fix: Correcting log output for scheduler interval value

__tests__/unit/validators/validator.test.js, docs/changelog.rst, docs/validators/commit.rst, docs/validators/stale.rst, lib/errors/unSupportedSettingError.js, lib/validators/and.js, lib/validators/approvals.js, lib/validators/assignee.js, lib/validators/changeset.js, lib/validators/commit.js, lib/validators/dependent.js, lib/validators/description.js, lib/validators/label.js, lib/validators/milestone.js, lib/validators/or.js, lib/validators/project.js, lib/validators/size.js, lib/validators/stale.js, lib/validators/title.js, lib/validators/validator.js, package.json
User Story : As a user, i want to know if there are unknown settings in my config so that i can fix it.
closes #289
=> feat: validate settings and throw error if unexpected or unknown settings are found

lib/validators/changeset.js, lib/validators/description.js, lib/validators/label.js, lib/validators/milestone.js, lib/validators/project.js, lib/validators/title.js
`regex_flag` setting were missing from #307 
closes #307
=> fix: `regex_flag` to supported Settings

__tests__/unit/actions/comment.test.js, lib/actions/comment.js
=> fix: Error occurring while removing error comments

README.md
=> docs: Small fix for the README for labels action

package.json
Update lodash to address a vulnerability reported by Snyk.io:
https://snyk.io/vuln/SNYK-JS-LODASH-567746
=> chore: Update lodash

lib/flex.js
this bug was introduced in #338
=> fix: bug where pass, fail or error is undefined

docs/actions/check.rst
Add the default checks logic to docs
closes #341
=> docs: add default checks logic

__fixtures__/unit/helper.js, __tests__/unit/configuration/configuration.test.js, lib/configuration/configuration.js, lib/validators/changeset.js, lib/validators/contents.js, lib/validators/dependent.js, lib/validators/options_processor/owners.js, lib/validators/size.js
fix a bug where only 30 files are grabbed from a PR and rest is ignored
closes #350
=> fix: bug where file limit is 30 on a PR

docs/changelog.rst, lib/actions/merge.js
fix the error string in merge fail error
=> fix: merge error

__tests__/unit/validators/stale.test.js, docs/changelog.rst, docs/validators/stale.rst, lib/validators/stale.js
=> feat: Enhance matching criteria for the stale validator

__tests__/unit/actions/comment.test.js, docs/changelog.rst, lib/actions/comment.js
=> fix: Fix the comment action to work correctly with the scheduler

__tests__/unit/actions/close.test.js, __tests__/unit/actions/labels.test.js, docs/actions/close.rst, docs/actions/label.rst, docs/changelog.rst, lib/actions/close.js, lib/actions/labels.js
=> feat: Add support for labels and close actions for stale

__tests__/unit/validators/size.test.js, docs/changelog.rst, docs/validators/size.rst, lib/validators/size.js
=> feat: Allow specifying files to match (#5)

docs/changelog.rst, lib/mergeable.js
=> feat: Add support for custom scheduler interval

__fixtures__/unit/helper.js, __tests__/unit/actions/labels.test.js, docs/actions/label.rst, docs/changelog.rst, lib/actions/labels.js
=> feat: Add support to replace and delete labels

docs/validators/and.rst, docs/validators/approval.rst, docs/validators/changeset.rst, docs/validators/description.rst, docs/validators/label.rst, docs/validators/milestone.rst, docs/validators/or.rst, docs/validators/title.rst
A couple of additions based on feedback and also to make it some minor features more verbose
fixes #370
=> docs: Add missing documentations

__tests__/unit/validators/size.test.js, docs/changelog.rst, lib/validators/size.js
=> fix: Size validator - do not ignore hidden files by default

.gitignore, package-lock.json
committing package-lock.json so that we can have same environment to develop in
fixes #385
=> chore: add package-lock.json

package-lock.json, package.json
moving handlebars from dev dependencies to dependencies
=> chore: move handlebars from dev to dependencies

__fixtures__/unit/helper.js, __tests__/unit/configuration/configuration.test.js, docs/changelog.rst, docs/configuration.rst, lib/configuration/configuration.js
=> feat: Do not load modified unsafe config files from forks

__tests__/unit/validators/baseRef.test.js, docs/changelog.rst, docs/validators/baseRef.rst, lib/validators/baseRef.js
BaseRef-validator for pull_requests to check "destination branch" with must_include and must_exclude conditions
=> feat: added BaseRef-validator based on Title-validator

__fixtures__/unit/helper.js, __tests__/unit/configuration/configuration.test.js, docs/changelog.rst, lib/configuration/configuration.js, package-lock.json, package.json
=> feat: Add a config cache

docs/recipes.rst
- Minor indentation correction in recipe yml example for Greet a contributor.
=> docs: Identation in yml correction for greeting a new contributor.

__tests__/unit/actions/action.test.js, __tests__/unit/actions/comment.test.js, __tests__/unit/flex/flex.test.js, lib/actions/action.js, lib/actions/close.js, lib/actions/comment.js, lib/actions/labels.js
- Abstracted common code for Actions that support the `schedule` event.
- Added tests for the above.
=> chore: DRY schedule supported actions

docs/configurable.rst, docs/configuration.rst, docs/deployment.rst, docs/validators/headRef.rst
- Add missing documentation page from #439 
- Add configurable-variables-page to help with deployment
=> docs: add headRef and configurable.rst pages

__tests__/e2e/smoke.test.js, docs/changelog.rst, lib/configuration/lib/consts.js, lib/stats/extractValidationStats.js
Related issue: https://github.com/mergeability/mergeable/issues/446
Output:
=> Feat: easy to see logs in pr

.codecov.yml
Adding codecov threshold and target. Refer to https://docs.codecov.io/docs/commit-status
=> chore: add codecov config

__tests__/unit/validators/approvals.test.js, __tests__/unit/validators/options_processor/owners.test.js, docs/changelog.rst, lib/validators/approvals.js, lib/validators/options_processor/owners.js, lib/validators/options_processor/teams.js
Related Issue: https://github.com/mergeability/mergeable/issues/442
-- 
This PR follows the second idea which I've changed the alghorithm to fetch approved users membership states and if any of them are true, it will be counted.
=> fix: member listing pagination issue

.github/workflows/docker.yml, .github/workflows/release.yml, docs/changelog.rst
Fixes the docker workflows. They are currently enabled for this branch to ensure they run fine before merging into master.
Another PR will be opened to clean up that configuration.
related to #450
=> fix: if conditional in docker workflows

__fixtures__/unit/helper.js, __tests__/unit/actions/labels.test.js, lib/actions/labels.js
This was missing part of the probot upgrade in #456
=> chore: replace issues.replaceLabels with issues.setLabels

__tests__/unit/actions/checks.test.js, docs/changelog.rst, lib/actions/checks.js
Fixes #454
This PR introduces a new feature that allows having `checks` with status `in_progress`.
=> feat: Allow to have pending checks

.github/workflows/testing.yml
- minor update to names to make it more meaningful.
=> chore: minor update with job and workflow names.

lib/validators/options_processor/teams.js
one of the missing upgrades for #456
=> chore: change getMembershipInOrg to getMembershipForUserInOrg

lib/actions/merge.js, lib/utils/logTypes.js
Change throwing error on known errors to log instead on merge
=> chore: remove throwing error on known issue and log instead

lib/actions/comment.js, lib/utils/logTypes.js
new version of probot started crashed the app when old comments are attempted to deleted but 404 is returned
=> chore: catch and log errors when delete comment fail

docs/changelog.rst, lib/utils/logTypes.js, lib/validators/options_processor/deepValidation.js
=> fix: bug where HttpError is returning for deepvalidation

lib/actions/action.js, lib/actions/comment.js, lib/actions/merge.js, lib/flex/flex.js, lib/flex/lib/logAndProcessConfigErrors.js, lib/flex/lib/processWorkflow.js, lib/interceptors/checkReRun.js, lib/mergeable.js, lib/validators/validator.js
rename eventId in logs to event_id for consistency
=> chore: rename eventId to event_id for consistency

docs/changelog.rst, docs/configuration.rst, docs/options/begins_with.rst, docs/options/ends_with.rst, docs/options/jira.rst, docs/options/max.rst, docs/options/min.rst, docs/options/must_exclude.rst, docs/options/must_include.rst, docs/options/no_empty.rst, docs/options/required.rst
This PR adds docs for validator options.
Sample SS:
=> docs: added options to docs

__fixtures__/unit/helper.js, docs/changelog.rst, lib/filters/options_processor/topics.js
The cache ENV used was incorrect, this PR fixes it
=> fix: Cache now use correct env

__tests__/unit/validators/approvals.test.js, docs/changelog.rst, docs/validators/approval.rst, lib/validators/approvals.js
=> feat: add `limit.users` option to approval validator

docs/configuration.rst
=> docs: add reusabe config section

docs/configuration.rst, docs/recipes.rst
closes https://github.com/mergeability/mergeable/issues/557
closes https://github.com/mergeability/mergeable/issues/558
Edit: i added closes in front of the issue number so merging this PR will auto-close them
=> docs: multiple recipes and name

__tests__/unit/filters/payload.test.js, docs/changelog.rst, docs/configuration.rst, docs/filters/payload.rst, lib/eventAware.js, lib/filters/payload.js
This will support the use case described in #398 
closes #398
=> feat: add payload filter

__tests__/unit/github/api.test.js, lib/actions/action.js, lib/actions/checks.js, lib/github/api.js
refactor the following github api calls:
- checks.create
- checks.update
=> refactor: github_api/checks

__tests__/unit/github/api.test.js, __tests__/unit/settings/settings.test.js, __tests__/unit/validators/contents.test.js, lib/configuration/configuration.js, lib/github/api.js, lib/settings/settings.js, lib/validators/contents.js, lib/validators/options_processor/owners.js
refactor `repos.getContents` call
=> refactor: github_api/repos:getContents

__fixtures__/unit/helper.js, __tests__/unit/github/api.test.js, lib/actions/labels.js, lib/github/api.js, lib/validators/label.js
- addLabels
- setLabels
- listLabelsOnIssue
=> refactor: github_api/issues:labels

__fixtures__/unit/helper.js, __tests__/unit/github/api.test.js, lib/actions/assign.js, lib/github/api.js
- addAssignees
- checkIfUserCanBeAssigned
=> refactor: github_api/issues:assignees

__fixtures__/unit/helper.js, __tests__/unit/actions/comment.test.js, __tests__/unit/github/api.test.js, lib/actions/comment.js, lib/github/api.js
- addComment
- deleteComment
- listComments
=> refactor: github_api/issues:comments

__fixtures__/unit/helper.js, __tests__/unit/github/api.test.js, lib/actions/close.js, lib/github/api.js, lib/validators/options_processor/deepValidation.js
=> refactor: github_api/issues

__fixtures__/unit/helper.js, __tests__/unit/github/api.test.js, lib/github/api.js, lib/validators/options_processor/teams.js
- teams.listMembersInOrg
- teams.getMembershipForUserInOrg
=> refactor: github_api/teams

__tests__/unit/github/api.test.js, lib/github/api.js, lib/validators/project.js
- projects.listColumns
- projects.listForRepo
- projects.listCards
=> refactor: github_api/projects

__fixtures__/unit/helper.js, __tests__/unit/github/api.test.js, lib/actions/merge.js, lib/github/api.js, lib/validators/stale.js
- search.issuesAndPullRequests
=> refactor: github_api/search

__tests__/unit/github/api.test.js, lib/actions/request_review.js, lib/filters/options_processor/topics.js, lib/github/api.js, lib/validators/options_processor/owners.js
- repos.listCollaborators
- repos.getAllTopics
- repos.compareCommits
=> refactor: github_api/repos

__fixtures__/unit/helper.js, __tests__/unit/github/api.test.js, lib/actions/merge.js, lib/github/api.js
- pulls.merge
- pulls.checkIfMerged
=> refactor: github_api/pulls:merge

__fixtures__/unit/helper.js, __tests__/unit/github/api.test.js, lib/actions/merge.js, lib/actions/request_review.js, lib/github/api.js
- pulls.get
- pulls.requestReview
=> refactor: github_api/pulls

__tests__/unit/github/api.test.js, lib/github/api.js, lib/interceptors/interceptor.js, lib/interceptors/push.js, lib/validators/approvals.js, lib/validators/commit.js
- pulls.list
- pulls.listCommits
- pulls.listReviews
=> refactor: github_api/pulls:lists

__tests__/unit/validators/changeset.test.js, docs/changelog.rst, docs/validators/changeset.rst, lib/validators/changeset.js
This PR implements the changes described in https://github.com/mergeability/mergeable/issues/550
Thanks to Bloomberg L.P. for letting us contribute to Mergeable.
=> feat: Filter specific status of files in changeset

docs/changelog.rst, lib/filters/options_processor/topics.js
Small fix for GithubAPI response
=> fix: Await GithubAPI topics response

docs/changelog.rst, helm/mergeable/templates/deployment.yaml
This PR updates deployment.yaml template to add support for labels provided from values files.
=> feat: support deployment labels from values

README.md
This PR updates/fixes example links in the README.md.  No code changes.
@jusx @shine2lay I wasn't sure where in the docs y'all want to link to.  Please advise 😉
=> fix: readme example links

lib/mergeable.js, package-lock.json, package.json
This is to support the latest version of `probot`. 
NOTE: @jusx and @shine2lay please let me join as one of the maintainers here 😄
=> chore: add support for latest version of `probot`

__tests__/unit/actions/labels.test.js, docs/changelog.rst, lib/github/api.js
=> fix: Send correct payload for changing labels
