- README.md
- __tests__/approvals.test.js
- __tests__/label.test.js
- __tests__/milestone.test.js
- __tests__/title.test.js
- circle.yml
- index.js
- lib/approvals.js
- lib/label.js
- lib/milestone.js
- lib/title.js
- package.json
- Add a feature to prevent PR from being mergeable when the milestone configured does not match the milestone set on the PR.
- Updated README.
> (feat) Add milestone as a configurable option to determine mergeability.

- README.md
- __tests__/configuration.test.js
- __tests__/handler.test.js
- lib/handler.js
- Based on configuration, exclude mergeable checks by specifying comma separated list of checks.
> (feat) Exclude mergeable checks with configuration

- __tests__/handler.test.js
- lib/handler.js
- Create `pending` status on PR before mergeable validations.
- Add tests. Improved handler test to ensure test failures bubble up by waiting for the promise.
closes #17
> Create pending status before validating.

- __tests__/title.test.js
- lib/processor.js
- lib/title.js
A second attempt at enforcing consistency in title by putting using a library to allow for re-usability and easily add more filters. 
@jusx I changed the `include` and `exclude` to `must-include` and `must-exclude` respectively to avoid confusion. 
Since we can also add many different filter, i think it make sense to show all the things that failed, I turned the `description` field into an array which holds all the errors. Backward compatibility is maintained so `description` can also be a string as well.
closes #15
> enforce consistency in title + tests

- __tests__/title.test.js
- lib/processor.js
fix `must-include` to `must_include` instead
added other filter cases: `min`, `max`, `begins_with`, `ends_with`, `no_empty`
allow for sub filter: `regex`, `min`, `max`, `match`, `message` and `enabled`
> allow advance settings in title

- __tests__/approvals.test.js
- lib/processor.js
closes #31 
instead of 
```
min: 5
message: '...'
```
this was implemented
```
min: 
count: 5
message: '...'
```
> advance setting for approval implemented

- lib/handler.js
this was caused because checks is expecting context.payload.pull_request and didn't find it
> fix bug where adding milestone throws error

- README.md
I have changed the order of permissions to the order they appear on GitHub so the users don't have to jump around. I have also added a settings section for the required parameters when setting up a new app. Finally, I have added the steps to run a local deployment.
Let me know what you guys think.
> Added the missing part about local deployments

- __fixtures__/helper.js
- __tests__/dependent.test.js
- docs/README.md
- lib/dependent.js
- lib/handler.js
Goals
---
This PR closes #36 
Details
---
- Added a validator that process on the `dependent` settings
- Wrote full unit test for the added files
- Tested Manually
The following settings can now be added to the configuration 
Note *** : this only work under `pull_requests:` setting
```
dependent:
files: [] // list of file where if one is modified, all must be modified
message: 'Custom message'
```
> (feat) Validate dependent files

- .github/mergeable.yml
- index.js
We are scheduling checks to fetch every 2 seconds. That's too much. It will now just use the default of every 1 hour.
Every 2 secs will cause performance problems on first install into an org with a lot of repos.
> Bugfix: Stale Reminder Performance

- __tests__/label.test.js
- lib/processor.js
Goal 
---
closes #74 
This other validators such as description, title, reviewers, etc... 
Details 
---
example config:
``` 
mergeable:
pull_requests:
label: 
or: 
- and: 
- must_include:
regex: 'release note: yes'
message: 'Please include release note: yes'
- must_include: 
regex: 'lang\\/core|lang\\/c\\+\\+|lang\\/c#'
message: 'Please include a language label'
- must_include: 
regex: 'release note: no'
message: 'Please include release note: no'
```
example output : 
When non of the required label is set
When only 'release note: yes' label is provided
When only `lang/core` label is provided
> add `and` and `or` sub options to processor

- docs/README.md
- index.js
- package.json
Fixes stale. The scheduler was commented out and hence it was not running stale.
- Ensure scheduler is started.
- Added `dev` script to start with NODE_ENV set to development.
- scheduler is set to much shorter intervals in development to allow for debugging and testing.
> (bugfix) Start scheduler for stale 

- __tests__/configuration/configuration.test.js
- lib/configuration/configuration.js
Preserve version 1 functionality.
- Clean up flex checks in `configuration/configuration` since it is only used then flex is turned on. The checks are redundant.
- Update unit tests for `configuration/configuration`!
> Correct Configuration When Loading with Version 1

- __tests__/configuration/configuration.test.js
- lib/configuration/configuration.js
- lib/dependent.js
Goal
---
When an Event is Pull_request, use the head branch's config file instead of the master branches
Context
---
This will allow user to test different settings and see how it works before merging it into the code base
> if event is pull_request, use the config file from head branch of PR

- __tests__/configuration/transformers/v2Config.test.js
- lib/configuration/configuration.js
- lib/configuration/lib/consts.js
- lib/configuration/transformers/v1Config.js
- lib/configuration/transformers/v2Config.js
- Feature: To ensure that there are default `pass`, `fail`, `error` actions for pull_request recipes.
- Refactor: Rename constant so that it is clear it's for `pull_request` events only.
> Feature: Default Actions for V2 Config

- __fixtures__/helper.js
- __tests__/validators/approvals.test.js
- lib/validators/options_processor/owners.js
- Owners file may not exist but in `flex` mergeable crashes. Handle the case where there's no owners file properly.
- Add test for when there is no owners file.
> Fix approvals for when ownersfile does not exist

- __tests__/actions/comment.test.js
- __tests__/configuration/configuration.test.js
- __tests__/configuration/transformers/v1Config.test.js
- __tests__/validators/stale.test.js
- lib/actions/comment.js
- lib/configuration/configuration.js
- lib/configuration/transformers/v1Config.js
- lib/validators/stale.js
Make `stale` work in flex. 
- Update comment to execute based on results of validators. Look for schedule results and comment appropriately.
- Update v1 transformer to output correct format for schedule.repository event.
- Update `Stale` validator to focus only on finding stale issues and/or pr -- it shouldn't be creating comments in the new flex.
- Update all relevant unit tests
> fix: stale

- .circleci/config.yml
- circle.yml
- docs/README.md
The `no_empty` suboption for `description` was documented wrongly with a dash instead of underscore.
> doc: fixes no_empty suboption for description examples.

- lib/validators/project.js
Context
---
Currently the input for project validators is `[Object]`
> display the proper project names

- __tests__/actions/checks.test.js
- __tests__/configuration/configuration.test.js
- __tests__/flex.test.js
- lib/actions/action.js
- lib/actions/checks.js
- lib/configuration/configuration.js
- lib/flex.js
Currently, when any problem is found with the configuration an error is thrown with no feedback given to the user:
1. A badly formatted YML is encountered
2. Version is invalid
3. `mergeable` node is missing.
The result is that the checks are never completed and the status stays at `queued` and is never `completed`.
fixes #154 
- Configuration while loading yml will validate and collect errors instead of throwing.
- Flex executor now creates a check suite if there is invalid configuration with a `cancelled` conclusion so as not to leave the check suite hanging.
> fix(configuration): Bad YML with no user feedback

- __tests__/flex.test.js
- lib/flex.js
Check if the event triggered is relevant before invoking `beforeValidate` on any `Action`s
fixes #168 
- Added unit tests for checking proper before and after validate invocations.
- Added checks for all recipes and it's events before invoking beforeValidate.
> fix(flex): before validate invocation

- __tests__/validators/approvals.test.js
- __tests__/validators/options_processor/options/or.test.js
- lib/validators/approvals.js
fixes #174 
- Added more tests to `OR` operands to improve coverage.
- Fix the logic to find approvers in the PR reviews. It should not take into account the comment after an approval is made. Since it does not approve or reject a PR we filter it out all together.
- Add test to cover all edge cases for review states.
> fix(approvals): Should not fail when reviewer approved and later comment

- __tests__/validators/approvals.test.js
- lib/validators/approvals.js
Should take care of #174 
- The GH API payload returns the states in past tense, we coded as a verb (action) as documented for submission. Changed to evaluating past tense of the verb for `COMMENT`
> fix(approvals): finding approved reviewers should properly ignore comments

- __tests__/validators/dependent.test.js
- lib/validators/dependent.js
In most cases we only want dependent files validated when a certain file is added/modified:
1. When `package.json` has changed, `package-lock.json` should exist but if we only have `package-lock.json` updated, `package.json` does not need to be updated. This happens when running `
npm install` where packages have not changed but minor versions have been installed. (.i.e. using ~ or ^ like so `~1.2.0`)
2. When `Gemfile` has been changed, we want to validate `Gemfile.lock` -- however one can run the bundler to update the gem versions without updating the `Gemfile`. (i.e. pessimistic restriction like so: '~> 3.1.1' is used and bundler is run).
New settings allows for:
```yml
- do: dependent
changed:
file: package.json
files: ['package-lock.json', 'yarn.lock']
```
Where `changed.files` are …
> feat(dependent): Add ability to only validate files when a specific file is in the change-set

- package.json
Sets the license in package.json so that it matches the one contained in
the LICENSE file.
The license identifier is based on:
https://spdx.org/licenses/
> fix: Change license in package.json to match LICENSE file

- lib/validators/validator.js
This comment seems to be leftover from a previous version of this file
(2da0093e11bf40ca2803cc1eb4997581c87c8665).
The function it refers to now exists in eventAware.js along with the
same comment.
> fix: Remove leftover comment from validator.js

- lib/validators/options_processor/options/no_empty.js
At some point, logic was added in this file that checks whether `enabled
=== false`, and if so returns early with a warning.
As such, the validation logic that happens below this doesn't need to check
this condition again.
> fix: Remove unecessary condition from no_empty.js

- docs/deploy.md
Update the deployment docs a bit, to clarify a few things about running locally. I had a few issues running this app locally at first, such as with the webhook secret (the GitHub app page mentions it's optional, but the probot wouldn't work locally without one set).
Though this could just be my inexperience with Probots in general, and I am wary of just replicating the existing documentation that GitHub has :slightly_smiling_face:
> docs: Update deploy.md docs

- __fixtures__/helper.js
- __tests__/validators/options_processor/options/max.test.js
- __tests__/validators/size.test.js
- docs/README.md
- lib/validators/options_processor/options/max.js
- lib/validators/size.js
Hi, I noticed that in the README there was mention of adding a way to validate the size of PRs. This sounded like a useful feature, and is something I was interested in using the bot for at my work.
This PR is my attempt at adding this. I've tested it out locally, and it seems to work OK.
I'm still not very familiar with the codebase, so this might not be the right way to approach this - let me know what you think.
It's also quite simple at the moment: it only lets you specify a maximum size for the total, and only counts added or modified files. Let me know if you'd prefer it to be more flexible or if this is OK as a start (it should be fairly easy to change the behavior either way).
Apologies for the (ironically) somewhat large PR. I've tried to keep it small, but there are a couple of …
> feat: Add PR size validator

- docs/README.md
I realised that in https://github.com/jusx/mergeable/pull/192 , I only added an example snippet of this validator, but didn't add a description of it to the list of validators at the top.
This should document it a little clearer I hope.
> docs: Add 'size' validator to list of validators in README

- docs/README.md
The example had a message that didn't quite match the config setting,  which could be confusing.
> docs: Small fix to size validator example in README

- __fixtures__/helper.js
- __tests__/actions/checks.test.js
- __tests__/interceptors/checkReRun.test.js
- lib/actions/checks.js
- lib/flex.js
- lib/interceptors/checkReRun.js
- lib/interceptors/index.js
- lib/interceptors/interceptor.js
- package.json
- closes #152 
Adds the ability to re-run `checks`:
Note: This PR does not address the `Re-run all checks` link.
- Added interceptor middleware 
- Added check-rerun interceptor to update context during a check rerun so that validation can be run with the right payload.
> feat: Check Re-run

- __tests__/interceptors/milestoned.test.js
- lib/flex.js
- lib/interceptors/index.js
- lib/interceptors/milestoned.js
- Clean up `flex` module
- moved special case function catering to `demilestoned` and `milestoned` actions for issue event to an interceptor.
- Added tests for the interceptor
> refactor: move milestoned special case function to an interceptor -

- .env.template
- docs/deploy.md
Adds a .env.template file that can be easily copied and filled out in
order to run the app locally. Also updates the deploy.md docs to mention
using this file as an option.
> docs: Add .env.template for local development

- __tests__/actions/checks.test.js
- __tests__/metaData.test.js
- lib/actions/checks.js
- lib/metaData.js
Fixes a bug where `undefined` is being displayed in the detail section of the checks when validation passes.
- Only set metadata when check payload text exists. Text only exists when validation fails and metadata is only needed during this time.
- Update `MetaData.exists` to support undefined parameter.
> fix: check text display undefined in details when validation passes.

- docs/deploy.md
Clarify project permissions.
Add Repository Project permissions to list of Read-Only access setting.
> docs: Need read permissions to repo projects for private repos.

- lib/context.js
- lib/mergeable.js
Give us flexibility and allows us to upgrade to Probot 9.x without breaking changes. In 9.x the property `event` becomes a getter only property. We intercept webhook events and update the event property according to scenarios for workflow execution purposes.
- Introduce the Context class.
- Pass our own Context instance to the workflow. This will be the instance used by all of mergeable.
Another PR for abstracting the way mergeable creates a logger will be opened separately.
> refactor: Use the mergeable context instead to invoke the workflow.

- __fixtures__/helper.js
- __tests__/configuration/configuration.test.js
- __tests__/validators/approvals.test.js
- lib/actions/comment.js
- lib/configuration/configuration.js
- lib/validators/approvals.js
- lib/validators/dependent.js
- lib/validators/label.js
- lib/validators/options_processor/owners.js
- lib/validators/project.js
- lib/validators/size.js
- package.json
Update the 'probot' npm package to the latest version.
This requires a number of small changes to deprecated methods in the github
context API. A couple of these were breaking, but most were just
deprecation warnings.
The main motivation for this was to fix a bug where the PRIVATE_KEY
environment variable was not being correctly recognised if it was base64
encoded, thus preventing deployment of the bot. base64-encoded keys are
supported in later versions of the probot lib:
https://probot.github.io/docs/configuration/
Support for this was added in 7.1.0:
https://github.com/probot/probot/pull/624
> feat: Update probot package

- docs/README.md
This feature has arguably been implemented in https://github.com/mergeability/mergeable/pull/192  :)
> docs: Update roadmap in README

- __tests__/configuration/configuration.test.js
- lib/configuration/configuration.js
- lib/configuration/lib/consts.js
resolves #194 
- Only set defaults when no configuration is found in the repos.
- Change the default title regex to be more precise. It makes more sense to only check for `wip` in the beginning of the title.
- Change the default label regex to only look for "work in progress" and "do not merge."
> feat: defaults are only loaded when no configuration found

- __tests__/validators/approvals.test.js
- __tests__/validators/options_processor/assignees.test.js
- docs/README.md
- lib/validators/approvals.js
- lib/validators/options_processor/assignees.js
- lib/validators/options_processor/options/required.js
Adds an option to the `approvals.required` config for specifying that all PR assignees are required to approve. When set to true, it automatically adds all assignees to the list of required approvers, similar to how the `owners` option works.
> feat: Add option for requiring assignee approval

- .env.template
According to the probot documentation at
https://probot.github.io/docs/configuration/, the expected variable name is
`WEBHOOK_SECRET` and not `SECRET_TOKEN`
> fix: Fix the incorrect environment name

- __tests__/validators/size.test.js
- docs/README.md
- lib/validators/size.js
- package.json
The size validator 'ignore' option only allowed specifying absolute file
paths. This adds support for glob pattern matching to allow specifying
patterns to ignore.
This relies on the minimatch library (pulled in as a new dependency) to
perform the glob handling and conversion to regular expressions:
https://github.com/isaacs/minimatch
This addresses https://github.com/mergeability/mergeable/issues/217
> feat: Support glob patterns in size validator

- __tests__/configuration/configuration.test.js
- lib/configuration/configuration.js
FetchConfigFile would fail when trying to fetch a modified config from a PR living on a fork. It would try to use the pull_request's ref (aka the branch name) on the original repository, which would fail since said branch does not exist (github would return a 404).
To give a practical example: In SunriseOS, I made a PR that modified the configuration from my fork. Mergeable would attempt fetching https://api.github.com/repos/sunriseos/SunriseOS/contents/.github/mergeable.yml?ref=mergeable-v2 , which 404s.
There are two valid URLs we can try using:
- Using the PR's repo name: https://api.github.com/repos/roblabla/KFS/contents/.github/mergeable.yml?ref=mergeable-v2
- Using the PR's head SHA: https://api.github.com/repos/sunriseos/SunriseOS/contents/.github/mergeable.yml?ref=c333c15eb4215acfa …
> fix: FetchConfigFile from forked PR

- __tests__/validators/size.test.js
- docs/README.md
- lib/validators/size.js
This PR adds the ability to specify PR size types. 
```yml
- do: size
lines:
total:
count: 500
message: Change is very large. Should be under 500 lines of additions and deletions.
additions:
count: 250
message: Change is very large. Should be under 250 lines of additions 
deletions:
count: 500
message: Change is very large. Should be under 250 lines of deletions.
```
> feat: seperate PR size types: additions, deletions and total

- docs/README.md
I tried to copy and paste the checks setting in our readMe and ran into a few invalid configuration error.
Also added the default fail template since if user were to utilize other actions, the defaults are no longer applied so user will have to specify the defaults explicitly
> fix: and update checks in the readMe

- package.json
Upgrade to the latest versions of these packages. This should hopefully
also fix a prototype pollution vulnerability in lodash (which probots
also pulls in):
https://snyk.io/vuln/SNYK-JS-LODASH-450202
> fix: Upgrade probots and lodash packages

- __tests__/flex.test.js
- lib/flex.js
Current implementation of isEventInContext function allows matching for multiple events such as `issues` and `issuesComment`. This leads to a bug where if the config specify both those events as different `when`, unintended actions will be fired.
Solution:
strictly check for the correct event type instead of using `includes`
> fix: isEventInContext

- __fixtures__/unit/helper.js
- __tests__/unit/configuration/configuration.test.js
- __tests__/unit/interceptors/checkReRun.test.js
- __tests__/unit/interceptors/milestoned.test.js
- lib/configuration/configuration.js
- lib/interceptors/checkReRun.js
- lib/interceptors/milestoned.js
- lib/validators/approvals.js
- lib/validators/dependent.js
- lib/validators/size.js
The 'pullRequests' attribute on the GitHub context has been replaced by
'pulls' in Octokit since version 3 of `plugin-rest-endpoint-methods.js` and deprecated in earlier versions:
- https://github.com/octokit/rest.js/releases/tag/v16.43.0
- https://github.com/octokit/plugin-rest-endpoint-methods.js/releases/tag/v3.0.0
This was causing the bot to break for me when running locally. Seems the API has changed a little.
> fix: Replace deprecated pullRequests attribute

- __tests__/unit/configuration/configuration.test.js
- lib/configuration/configuration.js
- lib/flex.js
- package.json
closes #252 
Instead of creating default config, we create a 'success' check for PRs if no config were found. This is in order to communicate to the user that no configs were found.
> feat: Remove default config and add new default behaviour

- docs/README.md
Add a note in the readMe to address `owner` sub-options not working in private repos
closes #256
> docs: add a note about `owners` sub option not working in private repos

- __tests__/unit/validators/changeset.test.js
- docs/README.md
- lib/validators/changeset.js
new validator: `changeset` validate against the files in the PR
config 
```
- do: changeset
no_empty:
enabled: false # Cannot be empty when true.
message: 'Custom message...'
must_include:
regex: 'yarn.lock'
message: 'Custom message...'
must_exclude:
regex: 'package.json'
message: 'Custom message...'
begins_with:
match: 'A String' # or array of strings
message: 'Some message...'
ends_with:
match: 'A String' # or array of strings
message: 'Come message...'
min:
count: 2 # min number of files in a PR
message: 'Custom message...'
max:
count: 2 # max number of files in a PR
message: 'Custom message...'
```
closes #184
> feat: Changeset validator

- __tests__/unit/configuration/configuration.test.js
- lib/configuration/configuration.js
Add more checks in validating the config file 
added checks 
- `mergeable` node must not be empty
- for v2: check that `mergeable` is an Array
- for v2: each element in `mergeable` array has both `when` and `validate` keyword
- for v2: `validate` keyword must be non-empty and an array
closes #263
> feat: add more validations to configuration

- lib/actions/action.js
- lib/flex.js
- lib/validators/validator.js
Our logs are hard to parse because the JSON in the logs are not serialized currently there are multi-line message.
> fix: stringify json in logs

- __tests__/unit/validators/options_processor/options/must_exclude.test.js
- __tests__/unit/validators/options_processor/options/must_include.test.js
- docs/README.md
- lib/validators/options_processor/options/must_exclude.js
- lib/validators/options_processor/options/must_include.js
- package.json
add the ability for user to define regex_flag to be used in `must_include` and `must_exclude`
leaving 'i' option as default for backward compatibility. 
sample config 
```
- do: labels
must_exclude:
regex: 'ABC.js'
regex_flags: '' # putting '' will remove the default 'i' options 
```
closes #226
> feat: Regex flag to must_include and must_exclude sub options

- lib/actions/action.js
- lib/flex.js
- lib/mergeable.js
- lib/validators/validator.js
It seems the changes in #278 is in the right direction but it's still not enough as `bunyan` still truncate the log if the line is too long and put it into a new line which makes things much harder to parse. 
I am expecting these changes will fix the issue
> fix: serializing in logs

- __fixtures__/unit/helper.js
- __tests__/unit/validators/commit.test.js
- __tests__/unit/validators/label.test.js
- __tests__/unit/validators/options_processor/options/must_exclude.test.js
- __tests__/unit/validators/options_processor/options/must_include.test.js
- docs/README.md
- lib/validators/commit.js
- lib/validators/options_processor/options/must_exclude.js
- lib/validators/options_processor/options/must_include.js
Added a `commit` validator that runs validations against git commits
sample config
```
- do: commit
messsage:
regex: '^(feat|docs|chore|fix|refactor|test|style|perf)(\(\w+\))?:.+$'
message: 'Custom message' # Semantic release conventions must be followed
skip_merge: true #Optional, Default is true. Will skip commit with message that includes 'Merge'
oldest_only: false #Optional, Default is false. Only check the regex against the oldest commit
single_commint_only: false #Optional, Default is false. only process this validator if there is one commit
```
closes #241
> feat: commit validator

- .github/mergeable.yml
Remove setting in `mergeable.yml` are either redundant or no longer necessary
closes #276
> fix: remove unnecessary settings in mergeable.yml

- __tests__/unit/validators/dependent.test.js
- lib/validators/dependent.js
We are not handling error when `file` sub option is missing properly. This PR is to fix that.
closes #285
> fix: add error handling to dependent validator

- docs/README.md
Copy-pasted this example, got this error:
> Error: Failed to run the 'commit' validator because 'message' option is not found. Please check README for more information about configuration
> docs: fix typo in the commit check example

- docs/README.md
I'm on a roll today! 😂 A follow up for #287
This one was worse because it it didn't fail the config validation, just failed the `commit` check itself and  I couldn't figure out why it's failing.
> docs: fix another typo in the commit check example

- lib/actions/checks.js
Remove the extra log in check before and after validate functions
> fix: prevent double logging in check action

- .env.template
- __fixtures__/unit/helper.js
- __tests__/unit/configuration/configuration.test.js
- __tests__/unit/flex.test.js
- docs/README.md
- docs/deploy.md
- lib/configuration/configuration.js
Adds support for specifying default config files in a central repository.
This allows for providing default settings for Mergeable that can be
overriden in individual repos. The purpose is to make it easier to manage
Mergeable across a large number of repos.
The behaviour is quite basic, so there is no support for overriding individual
settings in the configs. Mergeable will use either the default file or the
file in the repo/PR, but never both.
The approach is based on the Probot library which when loading the
config file will look in a repo named '.github' as a fallback. Because
Mergeable can only be granted permission to a specific file path, the
default file needs a somewhat confusing path
('<org>/.github/.github/mergeable.yml').
Addresses: …
> feat: Add support for default config files

- __tests__/unit/actions/comment.test.js
- lib/actions/assign.js
- lib/actions/close.js
- lib/actions/comment.js
- lib/actions/labels.js
- lib/actions/request_review.js
In the #297 , I accidentally left out parameter changes to afterValidate.
This had a small impact on `comment` action but, it is very low impact.
> fix: after validate

- __fixtures__/unit/helper.js
- __tests__/unit/flex.test.js
- __tests__/unit/validators/approvals.test.js
- docs/changelog.rst
- docs/validators/approval.rst
- lib/errors/teamNotFoundError.js
- lib/validators/approvals.js
- package.json
Add the ability to limit the approval validator to team members
s
sample config:
```
- do: approvals
min:
count: 2 # Number of minimum reviewers. In this case 2.
message: 'Custom message...'
limit:
teams: ['org/team_slug']  # when the option is present, only the approvals from the team members will count
```
closes #236
> feat: allow approvals to be limited to team members

- .env.template
- __fixtures__/unit/helper.js
- __tests__/unit/actions/comment.test.js
- docs/actions/comment.rst
- docs/changelog.rst
- lib/actions/comment.js
Old comments are removed by default before creating a new one on an issue
new config : 
```
- do: comment
payload:
body: >
Your very long comment can go here.
old_comment: 'delete' # delete by default, if you wish to leave the old comments use 'leave'
```
closes #157
> feat: delete old comments before creating new one

- README.md
- __tests__/unit/actions/assign.test.js
- docs/actions/assign.rst
- docs/changelog.rst
- lib/actions/assign.js
**Usecase:** As a user I want to be able to automatically assign a PR/Issue not only to a predefined person but also to the author of the PR/Issue.
**Solution:** Besides allowing a fixed list of assignees one should be able to put in a placeholder like `@author` to assign the PR/Issue to the creator
**Sample usage:**
```yaml
version: 2
mergeable:
- when: pull_request.*, issues.*
name: 'Auto assign to author if no assignee is set'
validate:
- do: assignee
min:
count: 1
fail:
- do: assign
assignees: [ '@author' ]
```
**Remark:** I have no hard feelings about the placeholder name, I just used `@author` because the `@` is never part of a github username
> feat: assign PR/Issue to author

- __tests__/unit/mergeable.test.js
- lib/mergeable.js
This PR corrects the time confusion in scheduler. [Probot scheduler](https://github.com/probot/scheduler) takes miliseconds as trigger interval, but in the code this is mixed with seconds and it's not really clear. It's documented that scheduler runs every 2 seconds in dev mode, but in reality it runs every `60 * 60 * 2` miliseconds which is `7.2` seconds
> fix: Correcting schedule interval

- __tests__/unit/validators/stale.test.js
- docs/changelog.rst
- docs/validators/stale.rst
- lib/validators/stale.js
- package.json
Context
allow stale to only run if certain conditions are met
```
- do: stale
days: 20 # number of days ago.
type: pull_request, issues # what items to search for.
limit: # Optional, run only if the specific options are met
time_zone: 'America/Los_Angeles' # Optional, UTC time by default, for valid timezones see `here <https://momentjs.com/timezone/>`_
hours_between: ['9', '17'] # Optional, 24 hours by default, run only if [0] >= Hour Now <= [1]
days_of_Week: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'] # Optional, 7 days a week by default, specific the days of the week in which to run the validator
```
closes #221
> feat: limit option for stale validator

- lib/validators/size.js
Context
there was a typo the `size` validator's supported settings
closes #313
> fix: `size` ignore supported settings

- lib/validators/commit.js
Context
commit validator name had a typo + supported setting is missing `regex_flag` variable
> fix: commit validator supported Settings

- __tests__/unit/validators/and.test.js
- __tests__/unit/validators/approvals.test.js
- __tests__/unit/validators/assignee.test.js
- __tests__/unit/validators/changeset.test.js
- __tests__/unit/validators/commit.test.js
- __tests__/unit/validators/dependent.test.js
- __tests__/unit/validators/description.test.js
- __tests__/unit/validators/label.test.js
- __tests__/unit/validators/milestone.test.js
- __tests__/unit/validators/or.test.js
- __tests__/unit/validators/project.test.js
- __tests__/unit/validators/size.test.js
- __tests__/unit/validators/stale.test.js
- __tests__/unit/validators/title.test.js
- docs/validators/approval.rst
- lib/validators/approvals.js
- lib/validators/dependent.js
Context
fix the tests to make sure the `validateSetting` is called to make sure all the valid settings implemented are a part of `supportedSettings`
this PR includes fixes to the `supportedSettings` that were missing, which is currently breaking production for certain settings
> fix: test supported settings

- __fixtures__/unit/helper.js
- __tests__/unit/actions/merge.test.js
- docs/actions/merge.rst
- docs/changelog.rst
- lib/actions/merge.js
Context
Adds merge action 
example config 
```
- do: merge
merge_method: 'merge' # Optional , default is 'merge'. Other options : 'rebase', 'squash'
```
This feature does require more app permission so it won't work right now for mergeable
closes #201
> feat: merge action

- __tests__/unit/configuration/transformers/v2Config.test.js
- docs/actions/check.rst
- docs/changelog.rst
- lib/configuration/lib/consts.js
- lib/configuration/transformers/v2Config.js
Context
When user provide partial parameter list for checks option, fill in the rest using default values
for more context, see https://github.com/mergeability/mergeable/issues/233#issuecomment-632211789
> feat: fill in missing param for `checks` by using default values

- __fixtures__/e2e/helper.js
- __fixtures__/e2e/issue.listComment.response.json
- __fixtures__/unit/helper.js
- __tests__/e2e/smoke.test.js
- __tests__/unit/actions/comment.test.js
- docs/changelog.rst
- lib/actions/comment.js
- lib/flex.js
If there is an error during `action` execution, a error comment will be created.
Every time a new error comment is created, old error comments will be deleted
During the next mergeable run, if none of the action throws error, the error comment will be deleted
closes #312
> feat: display error comment if error occured during action execution

- __tests__/unit/validators/contents.test.js
- docs/changelog.rst
- docs/validators/contents.rst
- lib/validators/contents.js
config 
```
- do: contents
files: # determine which files contents to validate
pr_diff: true # If true, validator will grab all the added and modified files in the head of the PR
ignore: ['.github/mergeable.yml'] # Optional, default ['.github/mergeable.yml'], pattern of files to ignore
must_include:
regex: 'yarn.lock'
message: 'Custom message...'
must_exclude:
regex: 'package.json'
message: 'Custom message...'
begins_with:
match: 'A String' # or array of strings
message: 'Some message...'
ends_with:
match: 'A String' # or array of strings
message: 'Come message...'
```
sample output
closes #207
> feat: contents validator

- __tests__/unit/validators/size.test.js
- docs/changelog.rst
- docs/validators/size.rst
- lib/validators/size.js
sample config
```
- do: size
lines:
total:
count: 500
message: Change is very large. Should be under 500 lines of additions and deletions.
additions:
count: 250
message: Change is very large. Should be under 250 lines of additions
deletions:
count: 500
message: Change is very large. Should be under 250 lines of deletions.
ignore_comments: false #if true, comments will not be counted toward the lines count
```
closes #245
> feat: ignore_comments option for `size` validator

- __tests__/unit/validators/contents.test.js
- lib/validators/contents.js
- lib/validators/options_processor/owners.js
Address the case in `contents` validator when the content file is not found.
Behavior implemented : 
If content is not found the validator will `fail` and `filename (Not found)` will be added to failed file list
> fix: handle case when content is not found

- README.md
- __tests__/unit/configuration/transformers/v1Config.test.js
- docs/validators/approval.rst
- version1.md
GitHub expects `CODEOWNERS` not `CODEOWNER`, according to their documentation
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners
> fix: The file should be named CODEOWNERS

- __tests__/unit/configuration/transformers/v2Config.test.js
- lib/configuration/transformers/v2Config.js
Implemented strategy:
if all pass, fail or error are undefined, add default
If either pass, fail or error contain a `checks` action, add the default to others (to support use case where user only want to change one checks case)
else don't apply anything.
closes #330
> fix: remove edge case described in #330

- __tests__/unit/flex.test.js
- lib/flex.js
Context
currently, processPreAction execution all actions inside registry for each recipe when it should be that preAction should only be executed if recipe have action as one of the outcomes
closes #337
> fix: processPreAction to only call action relevant to the recipe

- __tests__/unit/actions/comment.test.js
- lib/actions/comment.js
Context
Old comments are not deleted properly because the app name is 'mergeable' instead of 'Mergeable' (what was implemented)
> fix: bug where old comments are not properly deleted

- package.json
Fixes:
https://snyk.io/vuln/SNYK-JS-CODECOV-585979
We deploy a forked instance of this bot in my org, and we use Snyk.io there which pointed us towards this fix.
> chore: Upgrade codecov

- docs/actions/check.rst
- docs/configuration.rst
- docs/validators/approval.rst
- docs/validators/contents.rst
- lib/actions/checks.js
- lib/interceptors/push.js
- lib/validators/approvals.js
- lib/validators/assignee.js
- lib/validators/changeset.js
- lib/validators/commit.js
- lib/validators/dependent.js
- lib/validators/description.js
- lib/validators/label.js
- lib/validators/milestone.js
- lib/validators/options_processor/teams.js
- lib/validators/project.js
- lib/validators/size.js
- lib/validators/title.js
A few fixes to prepare for mergeable 2.0
- Push event was missing `pull_request.push_synchronize` in supported events
- remove mentions of permissions needed
> fix: push event + add fix docs for mergeable 2.0

- lib/interceptors/push.js
context
some of the push event doesn't have `head_commit` property, for those we can just skip it
> fix: some push event doesn't have `head_commit` property

- __tests__/unit/interceptors/push.test.js
- lib/interceptors/push.js
fix for push interceptor throwing `can't find 'added' of null` error
> fix: push interceptor - part 2

- .github/mergeable.yml
- Added auto merging when mergeable is passing
- Added check to check if `docs/changelog.rst` is modified when the PR is a `feat or fix`
> chore: add merge and changelog to mergeable config

- docs/changelog.rst
- lib/validators/size.js
Add list of processed files in size validator's display
closes #366
> feat: display file processed in size validator

- docs/changelog.rst
Some of my PRs had wrong issue references in the change log. Also makes the months consistent?
> docs: Fix changelog references

- docs/changelog.rst
- lib/actions/merge.js
There weren't any API to check if all required status is done so the solution implemented here is to just not throw error if we see this specific type of error
> fix: don't throw error if required status is not done

- docs/actions/labels.rst
- docs/changelog.rst
- docs/configuration.rst
The name of the action is 'labels' to be contrasted with the name of
the validator which is 'label'.
The filename for the doc is modified accordingly as well.
> fix(docs): header in labels action doc

- docs/changelog.rst
- docs/recipes.rst
- lib/actions/close.js
- lib/actions/comment.js
- lib/actions/labels.js
> fix: Fix undefined error with blank validators

- __tests__/unit/actions/merge.test.js
- docs/changelog.rst
- lib/actions/merge.js
I split out the fix for #389 from #394 
This has the required test and doc fixes for #389 
@jusx @shine2lay please review and merge this before #394
> fix: Do not attempt to merge a pull request if the status is blocked

- .circleci/config.yml
- package-lock.json
- package.json
Update  old packages and the node version on circle CI. Also changes the caching logic to use package-lock instead of package.json
The old packages were vulnerable.
> chore: Update node packages

- .circleci/config.yml
- __fixtures__/unit/helper.js
- __tests__/unit/actions/merge.test.js
- docs/changelog.rst
- docs/recipes.rst
- lib/actions/merge.js
Fixes #395 
Better version of #394 
We need to add support for both `status.*` events and `check_suite.*` events since the former is used by CI like Jenkins/Circle CI and the latter is used by apps like `mergeable` and Github Actions.
> feat: Add the ability to auto-merge pull requests

- __tests__/unit/validators/headRef.test.js
- docs/changelog.rst
- lib/validators/headRef.js
Issue: https://github.com/mergeability/mergeable/issues/438
---
With this PR, developers can validate headRef (branch) with regex tags.
Sample:
```
- do: headRef
must_include:
regex: '(^|[-\/])(major|release|minor|feature|patch|issue|hotfix|dependabot\/|whitesource)[-\/](\b[A-Z][A-Z0-9]+-\d+\b).+$'
message: 'Your branch name should be like feature/SOME-TICKET-NUMBER-some-description`
```
> feat: headref validator

- __tests__/unit/configuration/configuration.test.js
- docs/changelog.rst
- lib/configuration/configuration.js
Fixes: #429
**Problem:**
Currently there is no way to control which mergeable configuration file will be used, if the one from the PR branch or the one from the default branch.
**Solution:**
This PR implements a new environment variable to control that while maintaining the previous behaviour
> feat: Add env to control which configuration file to use

- docs/changelog.rst
- helm/mergeable/.helmignore
- helm/mergeable/Chart.yaml
- helm/mergeable/templates/NOTES.txt
- helm/mergeable/templates/_helpers.tpl
- helm/mergeable/templates/deployment.yaml
- helm/mergeable/templates/hpa.yaml
- helm/mergeable/templates/ingress.yaml
- helm/mergeable/templates/namespace.yaml
- helm/mergeable/templates/service.yaml
- helm/mergeable/templates/serviceaccount.yaml
- helm/mergeable/templates/tests/test-connection.yaml
- helm/mergeable/values.yaml
Fixes : https://github.com/mergeability/mergeable/issues/435
**Problem:**
There is no easy way to install Mergeable into the Kubernetes cluster.
**Solution:**
This PR implements a helm-chart to install mergeable into the Kubernetes cluster.
> feat: Helm Chart implemantation for kubernetes

- docs/changelog.rst
- lib/validators/options_processor/teams.js
I have to keep take the shift back to old way, beucase it causes some problem as below:
````
HttpError: Empty value for parameter 'team_slug': undefined
at /app/node_modules/@octokit/rest/plugins/validate/validate.js:74:15
at Array.forEach (<anonymous>)
at /app/node_modules/@octokit/rest/plugins/validate/validate.js:42:12
at Array.forEach (<anonymous>)
at validate (/app/node_modules/@octokit/rest/plugins/validate/validate.js:15:23)
```
> fix: Shift fix in team slug pagination

- .dockerignore
- .github/workflows/docker.yml
- Dockerfile
- docs/changelog.rst
Fixes #427
This PR introduces a Docker image by adding a Dockerfile and an Actions pipeline to build and push to Docker Hub.
A Docker Hub account will be required and also is necessary to set repository secrets `DOCKERHUB_USERNAME` with the account name and `DOCKERHUB_PASSWORD` with the generated token.
> feat: Add docker image build and push

- __tests__/e2e/smoke.test.js
- docs/changelog.rst
- lib/configuration/lib/consts.js
This PR removes the last list element comma by properly using the `last` function.
So instead of this:
`2/2 Fail(s): HEADREF, DESCRIPTION,`
Will be this:
`2/2 Fail(s): HEADREF, DESCRIPTION`
> fix: Prevent add comma on last list element

- .github/workflows/docker.yml
- .github/workflows/release.yml
- .github/workflows/testing.yml
- docs/changelog.rst
Related issue: https://github.com/mergeability/mergeable/issues/450
---
This PR enables Github-Actions for PRs to test and upload coverage to codecov and release docker image after pushed to master.
For docker release to be worked;
You need to create 3 secrets;
- DOCKERHUB_PUSH - true/false to enable docker releasing
- DOCKERHUB_USERNAME - Docker hub username
- DOCKERHUB_TOKEN - Docker hub access token
- DOCKERHUB_REPO - Docker hub repo address (i.e. `mergeability/mergeable`)
> feat: GitHub actions

- lib/actions/comment.js
- lib/actions/merge.js
fix the log usage in #484 #479
Context : the functions calling `this` is outside of the class
> chore: make proper use log.info on recently merged PRs

- .github/workflows/testing.yml
- chore: update testing workflow node version to align with package.json
- fix: the npm command test-coverage invokes an upload to codecov. Remove redundant GH action to upload which is a dup.
- fix: to invoke CI on push in a PR branch
> chore: update testing action node version to align with package.json

- docs/changelog.rst
- lib/actions/comment.js
- lib/actions/request_review.js
- lib/interceptors/checkReRun.js
Includes following minor changes: 
- Make `review_request_fail_error` a log `info` instead of `error`
- add missing `actionObj` to deleteComment function
- skip checkRun if `ouptut` field is not present or `pull_request` is empty
> fix: minor bugs

- __fixtures__/unit/helper.js
- __tests__/unit/filters/repository.test.js
- docs/changelog.rst
- docs/filters/repository.rst
- lib/filters/options_processor/name.js
- lib/filters/repository.js
sample config
```
- do: repository
name:
must_include:
regex: 'my-repo-name'
must_exclude:
regex: 'other-repo-name'
```
https://github.com/mergeability/mergeable/issues/509#issuecomment-782806518
> feat: add `name` sub option to `repository` filter

- __tests__/unit/validators/approvals.test.js
- docs/changelog.rst
- lib/actions/handlebars/populateTemplate.js
- lib/validators/approvals.js
see the discussion in https://github.com/mergeability/mergeable/issues/509#issuecomment-783346365
output
> feat: add a info panel for 'limit' option in `approval` validator

- __tests__/e2e/smoke.test.js
- docs/changelog.rst
- index.js
- lib/mergeable.js
- lib/stats/githubPrometheusStats.js
- lib/utils/githubRateLimitEndpoint.js
- package-lock.json
- package.json
In order to better monitor mergeable, this PR adds two metrics-related endpoints that allow monitoring GitHub rate limiting.
Both endpoints are disabled by default, and can be enabled by setting their specific env to `true`.
`GET /metrics`
```
github_ratelimit_remaining_total{installationId="13882267"} 4972
github_ratelimit_limit_total{installationId="13882267"} 5000
```
`GET /github-ratelimit/:installationId`
```json
{"limit":5000,"used":36,"remaining":4964,"reset":1616674979}
```
> feat: Add rate limit related metrics/endpoint

- __tests__/unit/github/api.test.js
- lib/configuration/configuration.js
- lib/github/api.js
- lib/utils/logTypes.js
- lib/validators/changeset.js
- lib/validators/contents.js
- lib/validators/dependent.js
- lib/validators/options_processor/owners.js
- lib/validators/size.js
- lib/validators/validator.js
Refactor github api calls into an abstraction layer for two purposes:
- reusablility
- to catch and log errors 
Note: this PR only include one particular github API call, in order to keep the PR small. other github calls will be refactor in subsequent PRs
> refactor: githubAPI abstraction layer

- docs/changelog.rst
- helm/mergeable/templates/prometheus-servicemonitor.yaml
- helm/mergeable/templates/service.yaml
- helm/mergeable/values.yaml
With this PR, helm chart will deploy a `ServiceMonitor` resource capable of monitoring mergeable metrics.
> feat: add chart support to prometheus servicemonitor

- .gitignore
- __tests__/unit/validators/options_processor/options.test.js
- package-lock.json
- package.json
- scheduler/test.js
- Bumps jest from 24.0.0 to 26.6.3: Current v24.0.0 was released over 2 years ago
https://www.npmjs.com/package/jest/v/26.6.3
https://www.npmjs.com/package/jest/v/24.0.0
- Bumps nock from 13.0.5 to 13.1.0
https://www.npmjs.com/package/nock/v/13.0.5
https://www.npmjs.com/package/nock/v/13.1.0
> NOTE: jest v27 introduces several breaking changes that require further analysis to fix unhandled promises due to a 401 error code throw by the mocked server.
https://github.com/facebook/jest/releases/tag/v27.0.0
@shine2lay @jusx
> chore(deps): bump jest to latest v26.6 available version

- docs/actions/merge.rst
As I'm reading the documentation, I noticed that the support events in code do not match in the documentation (https://github.com/mergeability/mergeable/blob/master/lib/actions/merge.js#L20:L24).
> docs: update supported events for merge action

- __tests__/unit/validators/stale.test.js
- docs/changelog.rst
- docs/validators/stale.rst
- lib/validators/stale.js
See https://github.com/mergeability/mergeable/issues/565
This is a very small fix to ignore drafts in the stale validator.
> feat: Add `ignore_drafts` option to ignore drafts in stale validator

- __tests__/unit/validators/changeset.test.js
- __tests__/unit/validators/options_processor/options/must_exclude.test.js
- __tests__/unit/validators/options_processor/options/must_include.test.js
- docs/changelog.rst
- docs/options/must_exclude.rst
- docs/options/must_include.rst
- lib/validators/baseRef.js
- lib/validators/changeset.js
- lib/validators/contents.js
- lib/validators/description.js
- lib/validators/headRef.js
- lib/validators/label.js
- lib/validators/milestone.js
- lib/validators/options_processor/options/must_exclude.js
- lib/validators/options_processor/options/must_include.js
- lib/validators/title.js
Hi! :wave: Another PR. This solves our use case raised in #573 and allows `must_include` to be either a `string` or an `array.
I imagine this would be used in other places, but I'm not sure where.
> feat: Support must_include and must_exclude regex as an array

- __fixtures__/e2e/pr.payload.json
- __fixtures__/unit/helper.js
- __tests__/unit/actions/request_review.test.js
- docs/actions/request_review.rst
- docs/changelog.rst
- lib/actions/request_review.js
- lib/github/api.js
👋 This PR adds support for a `teams` option on the `request_review` action which will assign GitHub teams like the `reviewers` option does. 
I added tests which are passing, but I'm not sure about any other way to test since it's a marketplace app.
Closes #430
> feat: Add team assignment to `request_review` action

- __tests__/unit/actions/labels.test.js
- docs/actions/labels.rst
- docs/changelog.rst
- lib/actions/labels.js
This adds the `add`, `replace`, `delete` options for the `labels` action. Documentation was extended to include the new info, and labeled the old API as deprecated. I tested a bunch of scenarios with this with a local deploy and it's working great!
Closes #576
> feat: New labels API 

- docs/changelog.rst
- index.js
This fix allows running mergeable as a lambda function using probot/adapter-aws-lambda-serverless by checking that getRouter is defined (which it won't be if started within a lambda function).  This likely will also allow it to work in other serverless frameworks, however I didn't test against them so can't speak to that.
Fixes #586
> fix: Check that getRouter is defined before attempting to access it

- __fixtures__/unit/helper.js
- __tests__/unit/filters/baseRef.test.js
- docs/changelog.rst
- docs/filters/baseRef.rst
- lib/filters/baseRef.js
As a user of Mergeable i want to be able to execute validators only on PRs targeting a certain baseRef
```
- do: baseRef
must_include:
regex: '^master$'
message: 'Custom message...'
```
> feat: Add baseRef filter

- __tests__/unit/validators/baseRef.test.js
- docs/changelog.rst
- docs/validators/baseRef.rst
- lib/validators/baseRef.js
- The auto-merge workflow (using the `merge` action) listens to
`check_suite.*` events in addition to the more standard
`pull-request.*` and `pull_request_review.*`.
This workflow relies on branch protections to stop the merge while
the check_suite is running.
Since branch protections are usually setup **only** only on the
default branch it means PRs that are targetting non-default
branches are auto-merged by the workflow sometime before the check
suite has even completed (if `check_suite.*` is used).
- Add `check_suite.*` event support to the baseRef validator so that
auto-merge can be limited to the default branch.
- Add unit tests for `check_suite` events.
- Fix prior bug in `mockContext` fixture when using the `baseRef` option.
The passed in `baseRef` value was not being set in the …
> feat: Add more supported events to baseRef validator

- __tests__/unit/validators/baseRef.test.js
- docs/changelog.rst
- docs/validators/baseRef.rst
- lib/validators/baseRef.js
- For status events the commit sha in the payload is used to make an
octokit request to fetch the pull requests to which the commit
belongs.
The pull requests are filtered to just the open ones.
The validator than check the base refs of these open pull requests.
- Add unit tests to cover new functionality
- Addresses #395
> feat: add support for status events to baseRef validator

- docs/recipes.rst
Added a recipe for validating commits and restricting PRs based on commit message semantics.
The current list of recipes did not have this covered, so adding in!
> Chore: Update recipes.rst

- .github/mergeable.yml
- __tests__/unit/actions/merge.test.js
- docs/actions/merge.rst
- docs/changelog.rst
- lib/actions/merge.js
Added a merge setting options called `commit_title` and `commit_message` that allow the user to control the merged commit message. These are templates that use the PR object as variables, so you can use the PR title, body, and number, for example. This allows users to set rules requiring certain commit messages without forcing the user to squash and `git push --force`. If we want the commit message to always contain the ticket, just force the user to update the PR title instead of pushing again.
> feat: Add an option to use PR title as commit message

- __tests__/unit/validators/changeset.test.js
- docs/changelog.rst
- lib/validators/changeset.js
This adds the ability to use the `all` option on `must_include` and `must_exclude` inside the changeset validator. The code was already there, but it wasn't allowed in the schema. This allows it in the schema.
Relates to https://github.com/mergeability/mergeable/issues/595
@shine2lay
> feat: Allow all option on must_include and must_include inside changeset validator

- docs/changelog.rst
- docs/recipes.rst
Section is not shown as code but as commented text.
> fix: correct indentation on documentation

- helm/mergeable/Chart.lock
- helm/mergeable/Chart.yaml
- helm/mergeable/values.yaml
Following the enforcement of the new [bitnami helm charts repository retention policy](https://github.com/bitnami/charts/issues/10539), this chart doesn't install properly anymore and bumping the version of the `bitnami/redis` chart is easy enough.
> chore(fix): Bump bitnami/redis to version 16.12.1

- docs/actions/request_review.rst
- docs/changelog.rst
I noticed that the `request_review` in its class does not match the example provided in the documentation.
> fix: supported events for `request_review` action

- __tests__/unit/validators/commit.test.js
- docs/changelog.rst
- docs/validators/commit.rst
- lib/validators/commit.js
Adding a newest_only boolean setting to commit validation as we require last commits to contain [patch|minor|major|no-version] for auto-versioning.
> feat: Add newest_only commit validation setting

- .github/workflows/docker.yml
- .github/workflows/testing.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- __tests__/unit/validators/description.test.js
- docs/changelog.rst
- lib/validators/description.js
In case, the payload `body` somehow returns undefined or null, we set the fallback value to an empty string.
> fix: set fallback value for `description` payload

- __tests__/unit/validators/options_processor/options/no_empty.test.js
- docs/changelog.rst
- lib/validators/options_processor/options/no_empty.js
This is to set fallback for `no_empty` options processor.
> fix: set fallback for `no_empty` options processor

- __tests__/unit/actions/merge.test.js
- __tests__/unit/validators/lastComment.test.js
- docs/changelog.rst
- docs/validators/last comment.rst
- lib/actions/merge.js
- lib/eventAware.js
- lib/filters/payload.js
- lib/validators/lastComment.js
Originally I thought this could be implemented as a filter (https://github.com/mergeability/mergeable/issues/639), but after giving it more thoughts, validator makes more sense.
The use case here is that developers can add a comment `merge` to trigger the `merge` action.
<details>
<summary>GIF</summary>
</details>
Thanks to Bloomberg L.P. for letting us contribute to Mergeable.
> feat: Add last comment validator

- __tests__/unit/filters/not.test.js
- __tests__/unit/validators/not.test.js
- docs/changelog.rst
- docs/configuration.rst
- docs/operators/and.rst
- docs/operators/not.rst
- lib/filters/and.js
- lib/filters/lib/logicalConnectiveValidatorProcessor.js
- lib/filters/not.js
- lib/filters/or.js
- lib/validators/lib/logicalConnectiveValidatorProcessor.js
- lib/validators/not.js
- lib/validators/or.js
Add a `not` operator (for filters and validators) to achieve functional completeness.
This enables each filter or validator to be negated, and is useful for filter/validator options that do not support negation.
For example, one could use `not` before the [`Dependent` validator](https://mergeable.readthedocs.io/en/latest/validators/dependent.html) to validate that certain files were NOT modified in a PR.
I created a new `not` filter and also a `not` validator.
It works exactly like its `and` and `or` counterparts.
Moreover, I renamed `andOrValidatorProcessor` to `logicalConnectiveValidatorProcessor` (for both filter and validator lib) and added the following section to it (shortened):
```js
if (name === 'Not') {
if (count !== 1) {
return consolidateResult([constructError(/* ... */)], …
```
> feat: Add Not operator

- __tests__/unit/filters/author.test.js
- docs/changelog.rst
- docs/filters/author.rst
- lib/filters/author.js
- lib/filters/options_processor/options/team.js
Add a way to change behavior based on team membership.
This PR adds the `team` option to the `author` filter.
If the `team` is set, then it is verified that the `author` is part of the team, otherwise, the filter fails.
Together with #695, this enables checking whether an author is _not_ part of a team.
I added `team: 'string'` to the supported settings of the author filter.
Then, I added a `TeamProcessor` that uses the existing functionality for `Teams` from the `validators` to check whether the user is part of the team.
> feat: Add team option to author filter

- docs/actions/check.rst
- docs/changelog.rst
- lib/actions/checks.js
The checks action should be able to support every
pull_request and pull_request_review events like stated
in the documentation. For example support for some events
like pull_request.ready_for_review was not supported with
current implementation.
> fix: Extend checks supported events

- docs/deployment.rst
Found a link that was incorrectly formatted in the documentation, so decided to fix it.
I then spotted a few other syntax errors in the same area so updated them too.
> docs: Fix syntax, link and grammar in `deployment.rst`

- docs/recipes.rst
The existing recipe for `Only run rules if PR is not a draft` is erroneous.  `- do: payload` can only be used for a filter and not a validator.
A working recipe is proposed in this PR.
> docs: Fix erroneous recipe for draft PR filter

- __tests__/unit/actions/lib/searchAndReplaceSpecialAnnotation.test.js
- docs/changelog.rst
- lib/actions/lib/searchAndReplaceSpecialAnnotation.js
There isn't a way to tag authors as the annotation `@@author` is replaced by ` author`.
```js
expect(searchAndReplaceSpecialAnnotations('this is @@author', payload)).toBe('this is @creator')
Expected: "this is @creator"
Received: "this is  creator"
```
```js
expect(searchAndReplaceSpecialAnnotations('this is something@author', payload)).toBe('this is somethingcreator')
Expected: "this is somethingcreator"
Received: "this is somethin creator"
```
Use a negative lookbehind `?<!\\\\${annotation}` to not match escaped annotations. The previous regex used to match any character before `@author` and would replace it with " author".
I have also added a couple of new tests to test the search and replace functionality.
> fix: search and replace of special annotations

- __tests__/e2e/smoke.test.js
- docs/actions/check.rst
- lib/configuration/lib/consts.js
This PR is based on this previous PR (https://github.com/mergeability/mergeable/pull/689). If this PR is merged, #689 could be closed because this contains the previous PR.
Following the same [blog post](https://www.kirkmahoney.com/blog/2009/01/the-test-results-that-were-ran/).
This PR includes:
- Typo fix
- Documentation fix
- Test E2E fix to match the typo.
> chore: fix typo "were ran" vs "were run" typo

- .github/workflows/release.yml
- .github/workflows/testing.yml
- docs/changelog.rst
- package-lock.json
- package.json
- scheduler/test.js
* Update release workflow as it is failing because new version of semantic-release requires node v20 or above
* Update testing workflow to use node v20
* Use recent version of GitHub actions for `actions/checkout` and `actions/setup-node`
* Bump `probot` to version `^13.0.2` as some tests were failing (especially smoke and scheduler test) in the previous version
* Bump `jest` and `nock` to latest versions --> nock was not mocking http requests in a few cases, don't know the exact reason but upgrading the version did work 🤷
* Cleanup nock stuff after scheduler test is done
> fix: update node version to v20 for release and testing workflow

- docs/changelog.rst
- lib/actions/assign.js
> fix: Always allow assigning author

- .dockerignore
- .github/workflows/docker.yml
- Dockerfile
- compose.yaml
- docs/changelog.rst
The old `Dockerfile` was using nodejs version 16 and not building at all.
This PR adds a new setup created with `docker init`.
It uses node 18 now as stated in the `package.json`.
These versions need to be kept in sync, so updating the nodejs version must also happen in the `Dockerfile`.
Executing the new docker image works:
> fix: Docker image not working

- __fixtures__/unit/helper.js
- __tests__/unit/actions/assign.test.js
- __tests__/unit/actions/checks.test.js
- __tests__/unit/actions/close.test.js
- __tests__/unit/actions/comment.test.js
- __tests__/unit/actions/labels.test.js
- __tests__/unit/configuration/transformers/v2Config.test.js
- docs/actions/assign.rst
- docs/actions/checks.rst
- docs/actions/close.rst
- docs/actions/comment.rst
- docs/actions/labels.rst
- docs/actions/merge.rst
- docs/actions/request_review.rst
- docs/changelog.rst
- docs/configuration.rst
- lib/actions/assign.js
- lib/actions/checks.js
- lib/actions/close.js
- lib/actions/comment.js
- lib/actions/labels.js
- lib/configuration/transformers/v2Config.js
This is intended to be used with lastComment validator, e.g.
```yaml
version: 2
mergeable:
- when: issue_comment.*
validate:
- do: lastComment
must_include:
regex: ^test$
pass:
- do: checks
status: 'success'
- do: assign
assignees: ['@author']
- do: comment
payload:
body: >
@author assigned!
fail:
- do: checks
status: 'failure'
```
> feat: Support 'issue_comment' event as trigger for actions

- __fixtures__/unit/helper.js
- __tests__/unit/actions/comment.test.js
- __tests__/unit/github/api.test.js
- __tests__/unit/validators/approvals.test.js
- __tests__/unit/validators/lastComment.test.js
- docs/changelog.rst
- lib/actions/comment.js
- lib/github/api.js
- lib/validators/lastComment.js
The GitHub API only returns 30 issue_comments by default. That can be problematic when the bot runs on PRs or Issues with a long discussion thread, since it won't be able to find the lastComment of a human or himself.
> fix: Respect all comments in lastComment validator and comment action

- __fixtures__/unit/helper.js
- docs/changelog.rst
- lib/actions/checks.js
- lib/actions/merge.js
Unfortunately #754 introduced a bug where could mergeable error when issue_comment event included a checks action and a comment is created on an Issue instead of an PR.
> fix: Comments on Issues should not trigger 'checks' action

- __fixtures__/unit/helper.js
- __tests__/unit/actions/action.test.js
- __tests__/unit/actions/assign.test.js
- __tests__/unit/actions/checks.test.js
- __tests__/unit/actions/comment.test.js
- __tests__/unit/actions/lib/searchAndReplaceSpecialAnnotation.test.js
- docs/actions/assign.rst
- docs/actions/comment.rst
- docs/annotations.rst
- docs/changelog.rst
- lib/actions/assign.js
- lib/actions/checks.js
- lib/actions/comment.js
- lib/actions/handlebars/populateTemplate.js
- lib/actions/lib/searchAndReplaceSpecialAnnotation.js
- lib/eventAware.js
one can now realize thinks like
```yaml
version: 2
mergeable:
- when: pull_request.opened, pull_request.edited, check_suite.rerequested
validate:
- do: title
begins_with:
match: ['AUTH', 'SOCIAL', 'CORE']
fail:
- do: checks
payload:
status: failure
title: 'Mergeable Run by @sender have been Completed!'
summary: |
- @author
- @sender
- @bot
- @repository
- @action
- {{formatDate}}
- PR payload properties:
- {{formatDate created_at}}
- {{formatDate updated_at}}
- {{title}}
- {{body}}
- {{assignee}}
- when: issues.opened, issues.edited
validate:
- do: title
begins_with:
match: ['AUTH', 'SOCIAL', 'CORE']
fail:
- do: comment
payload:
body: |
Annotations are replaced:
- @author
- @sender
- @bot
- @repository
- @action
- {{formatDate}}
- PR payload properties:
- {{formatDate created_at}}
- …
```
> feat: Add annotations @sender @bot @repository @action and template helper {{formatDate}}

- __fixtures__/unit/helper.js
- __tests__/unit/filters/author.test.js
- __tests__/unit/validators/author.test.js
- __tests__/unit/validators/lastComment.test.js
- docs/changelog.rst
- docs/deployment.rst
- docs/filters/author.rst
- docs/filters/payload.rst
- docs/recipes.rst
- docs/validators/author.rst
- docs/validators/lastComment.rst
- lib/filters/author.js
- lib/filters/options_processor/options/none_of.js
- lib/filters/options_processor/options/one_of.js
- lib/filters/payload.js
- lib/validators/author.js
- lib/validators/lastComment.js
- lib/validators/options_processor/listProcessor.js
- lib/validators/options_processor/options/none_of.js
- lib/validators/options_processor/options/one_of.js
- lib/validators/validator.js
Add options 'one_of' and 'none_of'.
Support in filters `payload`, `author`, and in action `lastComment` to filter comments authors.
Usage Example:
```yaml
version: 2
mergeable:
- when: issue_comment.*
name: "Merge pull requests when requested via comment"
filter:
- do: payload
sender:
login:
must_exclude:
regex: '\[bot\]$'
none_of: ['@author']
validate:
- do: lastComment
must_include:
regex: 'merge$'
message: 'Comment "merge" detected, going to merge the PR.'
comment_author:
one_of: ['@org/product-owners-team']
none_of: ['@author', 'shady-product-owner']
pass:
- do: merge
merge_method: "squash"
```
> feat: Add options 'one_of' and 'none_of' for filters and validators
